# Generated by Django 5.2.5 on 2025-10-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='reflection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
