# Generated by Django 5.2.5 on 2025-10-17 08:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motive',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='motive',
            name='habit_name',
        ),
        migrations.AddField(
            model_name='motive',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motive',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motive',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='motive',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motive',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motive',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
