# Generated by Django 5.2.5 on 2025-10-10 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('habit_type', models.CharField(choices=[('build', 'Build'), ('quit', 'Quit')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True, help_text="Describe when/where/how you'll do this habit")),
                ('commitment', models.PositiveSmallIntegerField(default=5, help_text='1-10 scale')),
                ('goal_duration', models.PositiveIntegerField(default=30, help_text='Goal duration in days')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('completed_today', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
