# Generated by Django 5.2.5 on 2025-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='habit',
            name='commitment',
            field=models.PositiveSmallIntegerField(default=5, help_text='Commitment level (1–10)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='plan',
            field=models.TextField(blank=True, help_text="Describe when, where, and how you'll do this habit"),
        ),
    ]
