# Generated by Django 5.2.5 on 2025-10-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growthfeed', '0002_remove_book_file_book_created_at_book_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
