# Generated by Django 5.2.5 on 2025-10-17 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Other', 'Other')], max_length=50)),
                ('daily_limit_minutes', models.PositiveIntegerField(default=60)),
                ('time_spent_today', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
